version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8082:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: rms
      MYSQL_ROOT_PASSWORD: password